name: Health check

on:
  schedule:
    - cron: "0/10 * * * *"

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@b716ccb6645355dd9fcce8002ce460e5474f7f00
        with:
          url: https://github.com